import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const AUTH=new Set(["operator","evidence_gate","manual_review"]),FORBIDDEN=new Set(["retrieval","reranker","dense_retriever","classifier","model","ranking"]),SCOPES=new Set(["public_discovery","authorized_public"]),STATUSES=new Set(["unreviewed","accepted_as_claim","corroborated","verified","rejected","revoked"]);
const STOPWORDS=new Set(["a","an","and","are","as","at","be","been","by","for","from","has","have","in","is","it","of","on","or","the","this","to","was","were","which","who","with","public","official","source","model","system","report","research","contact","lab","labs","laboratory","selector","catalog","company","organization","и","в","во","на","с","со","к","ко","из","по","для","что","это","как","какая","какой","какое","кто","модель","система","источник","публичный","публичная","компания","организация","разработчик","поколение","второе"]);
export const normalizeText=v=>String(v??"").normalize("NFKC").toLowerCase();
export function tokenize(v){const raw=normalizeText(v).split(/[^\\p{L}\\p{N}._:/-]+/u).filter(Boolean),out=[];for(const token of raw){if(!STOPWORDS.has(token))out.push(token);if(/[-/:.]/.test(token))for(const part of token.split(/[-/:.]+/).filter(Boolean))if(part.length>=2&&/\\p{L}/u.test(part)&&!STOPWORDS.has(part))out.push(part)}return out}
export function validateEvidenceRecord(r){const e=[];if(!r||typeof r!=="object"||Array.isArray(r))return["record must be an object"];for(const f of["schema_version","evidence_id","scope","source","provenance","content","identity_claim","evidence_level","acceptance","validity"])if(!(f in r))e.push(`missing ${f}`);if(r.schema_version!=="1.0")e.push("unsupported schema_version");if(!SCOPES.has(r.scope))e.push("private or unknown scope is not allowed in public evidence envelope");const s=r.source||{},v=r.validity||{},a=r.acceptance||{},c=r.identity_claim||{};for(const f of["source_id","source_type","channel","version","content_hash","observed_at"])if(!s[f])e.push(`source.${f} is required`);if(!v.source_version)e.push("validity.source_version is required");if(!v.source_content_hash)e.push("validity.source_content_hash is required");if(!v.index_generation)e.push("validity.index_generation is required");if(s.version&&v.source_version&&s.version!==v.source_version)e.push("source.version mismatch with validity.source_version");if(s.content_hash&&v.source_content_hash&&s.content_hash!==v.source_content_hash)e.push("source.content_hash mismatch with validity.source_content_hash");if(!STATUSES.has(a.status))e.push("unknown acceptance.status");if(!a.set_by)e.push("acceptance.set_by is required");if((a.status==="verified"||a.status==="corroborated")&&!AUTH.has(a.set_by))e.push("verified/corroborated acceptance requires operator/evidence-gate authority");if(FORBIDDEN.has(a.set_by)&&a.status!=="unreviewed")e.push("retrieval/model actors cannot set evidence acceptance authority");if(c.self_reported===true&&a.status==="verified"&&!AUTH.has(a.set_by))e.push("self-reported identity cannot be promoted to verified by retrieval/model output");if(r.scope==="public_discovery"){const z=JSON.stringify(r).toLowerCase();for(const f of["access_token","recovery_key","admin_token","bearer token","private_inbox_message"])if(z.includes(f))e.push(`public evidence contains forbidden private marker: ${f}`)}return e}
export function cloneAndSet(r,p,value){const c=structuredClone(r),parts=p.split(".");let x=c;for(let i=0;i<parts.length-1;i++){if(!(parts[i] in x))throw new Error(`unknown path: ${p}`);x=x[parts[i]]}x[parts.at(-1)]=value;return c}
export function evaluateMutationFixture(f,byId){if(f.query)return{fixture_id:f.id,category:f.category,structural_errors:[],semantic_expected:f.expected};const base=byId.get(f.base_evidence_id);if(!base)throw new Error(`missing base evidence: ${f.base_evidence_id}`);const m=cloneAndSet(base,f.mutation.path,f.mutation.to);if(f.actor)m.acceptance.set_by=f.actor;return{fixture_id:f.id,category:f.category,structural_errors:validateEvidenceRecord(m),semantic_expected:f.expected,mutated:m}}
function searchableText(r){return[r.source?.title,r.source?.url,r.source?.channel,r.source?.version,r.source?.content_hash,r.content?.text,r.identity_claim?.provider,r.identity_claim?.model_name,r.identity_claim?.model_identifier,r.identity_claim?.model_family,r.identity_claim?.agent_framework,r.identity_claim?.interaction_origin,r.evidence_level,r.acceptance?.status,r.validity?.invalidation_reason].filter(Boolean).join(" ")}
function exactSignals(r){return[r.source?.url,r.source?.version,r.source?.content_hash,r.identity_claim?.model_identifier].filter(Boolean).map(normalizeText)}
export function buildIndex(records){const docs=records.map(record=>{const tokens=tokenize(searchableText(record)),tf=new Map();for(const t of tokens)tf.set(t,(tf.get(t)||0)+1);return{record,tokens,tf,exact:exactSignals(record)}}),df=new Map();for(const d of docs)for(const t of new Set(d.tokens))df.set(t,(df.get(t)||0)+1);return{docs,df,avgdl:docs.reduce((s,d)=>s+d.tokens.length,0)/Math.max(docs.length,1),n:docs.length}}
function bm25(q,doc,index){const k1=1.2,b=.75;let score=0;for(const token of q){const f=doc.tf.get(token)||0;if(!f)continue;const dfi=index.df.get(token)||0,idf=Math.log(1+(index.n-dfi+.5)/(dfi+.5)),den=f+k1*(1-b+b*(doc.tokens.length/Math.max(index.avgdl,1)));score+=idf*((f*(k1+1))/den)}return score}
export function search(index,query,{topK=5,minimumScore=2}={}){const nq=normalizeText(query),q=tokenize(query);const scored=index.docs.map(doc=>{const exact=doc.exact.some(s=>s.length>=4&&nq.includes(s)),score=(exact?100:0)+bm25(q,doc,index);return{evidence_id:doc.record.evidence_id,score,exact,acceptance_status:doc.record.acceptance.status,evidence_level:doc.record.evidence_level,invalidated_at:doc.record.validity.invalidated_at}}).sort((a,b)=>b.score-a.score||a.evidence_id.localeCompare(b.evidence_id));const candidates=scored.filter(x=>x.score>=minimumScore).slice(0,topK);return{query,abstained:candidates.length===0,candidates}}
export function runBenchmark(fixture){const{corpus,benchmark}=fixture,recordErrors=corpus.records.flatMap(r=>validateEvidenceRecord(r).map(error=>({evidence_id:r.evidence_id,error})));if(recordErrors.length)return{recordErrors};const index=buildIndex(corpus.records),policy=benchmark.policy;let positives=0,noEvidence=0,h1=0,h3=0,h5=0,rr=0,correctAbstain=0;const failures=[],rows=[],byKind=new Map();for(const tc of benchmark.cases){const result=search(index,tc.query,{topK:policy.top_k,minimumScore:policy.minimum_score}),ids=result.candidates.map(c=>c.evidence_id);if(!byKind.has(tc.kind))byKind.set(tc.kind,{total:0,positive:0,hit5:0,abstain:0});const ks=byKind.get(tc.kind);ks.total++;if(!tc.relevant.length){noEvidence++;if(result.abstained){correctAbstain++;ks.abstain++}else failures.push({id:tc.id,kind:tc.kind,reason:"expected abstain",ids})}else{positives++;ks.positive++;const ranks=tc.relevant.map(id=>ids.indexOf(id)).filter(x=>x>=0).map(x=>x+1),best=ranks.length?Math.min(...ranks):Infinity;if(best<=1)h1++;if(best<=3)h3++;if(best<=5){h5++;ks.hit5++}if(Number.isFinite(best))rr+=1/best;else failures.push({id:tc.id,kind:tc.kind,reason:"relevant evidence not retrieved",ids})}rows.push({id:tc.id,kind:tc.kind,query:tc.query,relevant:tc.relevant,abstained:result.abstained,top:result.candidates.slice(0,5)})}const kind_metrics=Object.fromEntries([...byKind].map(([kind,s])=>[kind,{...s,recall_at_5:s.positive?s.hit5/s.positive:null,abstention_accuracy:s.positive?null:s.abstain/Math.max(s.total,1)}]));const metrics={positive_cases:positives,no_evidence_cases:noEvidence,recall_at_1:h1/positives,recall_at_3:h3/positives,recall_at_5:h5/positives,mrr_at_5:rr/positives,no_evidence_abstention_accuracy:correctAbstain/noEvidence,measurable_recall_gap_at_5:h5/positives<1};return{benchmark_version:benchmark.benchmark_version,corpus_version:corpus.corpus_version,policy,metrics,kind_metrics,failures,cases:rows}}
if(process.argv.includes("--benchmark")){const here=path.dirname(fileURLToPath(import.meta.url)),fixture=JSON.parse(fs.readFileSync(path.join(here,"frozen-v1.json"),"utf8")),result=runBenchmark(fixture);console.log(JSON.stringify(result,null,2));if(result.metrics?.no_evidence_abstention_accuracy!==1)process.exitCode=3}
